### ISSUE TITLE
Cannot save changed preferences

### ISSUE THREAD

**Issue by bsobor** [gaborposz/VideoFritter#2]
Application installed to the standard/default location.
When trying the save changed setting, the following error happens:
![image](https://user-images.githubusercontent.com/50029489/103137228-5a28ed80-46c7-11eb-8785-12099370f2c8.png)

Proposal save custom settings to %APPDATA% somewhere.

**Comment by gaborposz** [comment]
Fixed with commit [4d6fa5a573b11f9457258020b0e4fd23b6cffa9c](https://github.com/gaborposz/VideoFritter/commit/4d6fa5a573b11f9457258020b0e4fd23b6cffa9c).
