### ISSUE TITLE
Provide keyboard shortcuts

### ISSUE THREAD

**Issue by bsobor** [gaborposz/VideoFritter#7]
Add keyboard shortcuts to the controls. e.g. step with the arrows, mark begin/end of segment, etc. 
Currently spacebar executed the command the focus is on. But would be better to always do play/pause.

**Comment by gaborposz** [comment]
I created the following key assignment with 28fe25dd13b30352f6a99e47025d8953d1a45b41:
- Play/Pause: Spacebar
- Step backward & forward (1 frame): Left and Right arrows
- Jump backward & forward (to selection start-end or video start-end): Shift Left and Right arrows
- Set selection start/end: PageUp and PageDown
- Preview selection: Enter
- Play from selection start / to selection end: Home / End
- Export selection: E
- Next video: N

Any further suggestion?

**Comment by bsobor** [comment]
Sounds great, though, some questions:
- The "jump backward" / "jump forward" means the "Go to start" and "Go to end" buttons? Then it may better resonate to the Ctrl+Left and Ctrl+Right. While the Shift+Left/Right could be reserved to other - future - seeking operation,
- The "Export selection" means the "Export the current selection" button, where the export starts immediately? Or the "Add to export queue" which is a deferred export? In this case "Export the current selection" could have "E", and the "Add to export queue" could be Shift+E,
- Though, I think in this application the deferred export is the more frequently used functionality, meaning it shall have the simpler shortcut, while the immediate execution should have the "Shift" modifier one. But this sounds logically contradicting, as the simpler functionality is the immediate export, so that shall have the simples shortcut... like described above

Additionally, the
- "Open file" (rather should be called "Open File..." as it invokes a dialog) proposed to have Ctrl+O
- "View export queue" ("View Export Queue") proposed to have Ctrl+E
- "Settings", not a frequently used functionality, but if it would have shortcut then it should be Ctrl+P

**Comment by gaborposz** [comment]
Ok, I updated key assignments with 3e18b489540336534733a1f690cd1231d5d8049f, and now they look like this:
- Open File: _Ctrl-O_
- Open Settings: _Ctrl-P_
- Open Export Queue: _Ctrl-E_
- Open About box: _Ctrl-A_
- Play/Pause: _Spacebar_
- Step backward & forward (1 frame): _Left and Right arrows_
- Jump backward & forward (to selection start-end or video start-end): _Ctrl-Left and -Right arrows_
- Set selection start/end: _PageUp and PageDown_
- Preview selection: _Enter_
- Play from selection start / to selection end: _Home / End_
- Export selection: _E_
- Add to Export Queue: _A and Shift-E_
- Next video: _N_

**Comment by bsobor** [comment]
Alright, sounds great.
Looking forward the release.
