### ISSUE TITLE
Precision of step navigation

### ISSUE THREAD

**Issue by bsobor** [gaborposz/VideoFritter#8]
Step (forward/backward) goes by 100 ms (not by frame), but by 100 ms. 
This means 3 frames for a 30 fps recording (especially at time-lapse this could mean a lot).

How to go in smaller steps? e.g. provide possibility to able to edit the positions manually?

**Comment by gaborposz** [comment]
Fixed with 050e8bfbe6e9c1be055d73400d5b7f071dddf135.
The Step Fordward and Backward buttons now steps exactly one frame, instead of 100ms.
If further improvements are needed (e.g. jumping to an exact timestamp, or configuring the step size in frames) then please create another issue.
